version: '2.17.3'

services:
  ai-lab:
    build:
      context: .
    init: true
    tty: true
    volumes:
      - ./project:/project
      - ./notebooks:/notebooks
      - ./secrets:/secrets
    ports:
      - '8888:8888'